services:
  proxy:
    image: ferranhalborn/ctf_ad_proxy
    environment:
      - REDIRECT_PORT=6000
      - LISTEN_PORT=80
      - MASTER_IP=192.168.80.1
    # Remote
    ports:
      - target: 80
        published: 80
        mode: host
    # Local
    ports:
      - "6000:80"
    #network_mode: "host"

  challenge_simple:
    image: ferranhalborn/ctf_ad_base
    environment:
       - RESTRICTED_ACCOUNTS=["0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"]
    volumes:
      - "./challenge_simple:/root/challenge"

  challenge_proxy:
    image: ferranhalborn/ctf_ad_base
    environment:
       - RESTRICTED_ACCOUNTS=["0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"]
    volumes:
      - "./challenge_proxy:/root/challenge"

  challenge_erc777:
    image: ferranhalborn/ctf_ad_base
    environment:
       - RESTRICTED_ACCOUNTS=[]
    volumes:
      - "./challenge_erc777:/root/challenge"

  challenge_lotto:
    image: ferranhalborn/ctf_ad_base
    environment:
       - RESTRICTED_ACCOUNTS=[]
    volumes:
      - "./challenge_lotto:/root/challenge"

  challenge_token:
    image: ferranhalborn/ctf_ad_base
    environment:
       - RESTRICTED_ACCOUNTS=["0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"]
    volumes:
      - "./challenge_token:/root/challenge"
